### ISSUE TITLE
YaruNavigationPage: add optional space to the rail

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru.dart#458]

**Comment by Feichtmeier** [comment]
![Screenshot_20221213-193449](https://user-images.githubusercontent.com/15329494/207418040-adbfa925-3542-4e7b-93c2-71ef786d7221.png)

**Comment by Feichtmeier** [comment]
This is important when #455 lands and we want a titlebar-less look with a YaruTitlebar as the appbar of the pages in the YaruNavigationPage

Anyone of you could take a shot at this @jpnurmi @Jupi007 ?

**Comment by Jupi007** [comment]
I'm not sure to exactly understand what you mean.
Can't we just create a `Scaffold` with a `YaruNavigationPage` as child: 

![image](https://user-images.githubusercontent.com/36476595/207428627-5d857207-f8f8-4d77-9ca4-009d40228fd0.png)

Because, add an empty space to the rail will look weird I think 🤔

Btw, nice draw :D

**Comment by jpnurmi** [comment]
I haven't really looked into this yet but wouldn't you put the "empty" area into `YaruWindowTitleBar`? The idea is that `Yaru(Window)TitleBar` could host any content. The most basic use is a textual title, but for example, Workshops would put a `TabBar` there whereas Settings and Software could put something that matches the master/rail, right?

**Comment by Feichtmeier** [comment]
sorry for the crappy drawing.. was at the smartphone when I had this brain fart

![grafik](https://user-images.githubusercontent.com/15329494/207431007-87fc9f5a-3b4e-4ef2-8920-92a40ebd00dc.png)

ofc, we could also add a row to the YaruTitlebar with a first Widget as thick as the navigationrail, but since the width of the navigationrail depends on its label style, this could be a bit annoying to set up

**Comment by Jupi007** [comment]
Okay I understand better now.
But this mean have an empty space isn't it?

![Capture d’écran du 2022-12-13 20-57-38](https://user-images.githubusercontent.com/36476595/207431936-4e971d6b-6b61-40ef-a356-f1f868431e06.png)

**Comment by Feichtmeier** [comment]
yeah it's not optimal... 

or something like this
![grafik](https://user-images.githubusercontent.com/15329494/207432581-f8c58c1a-9676-4407-95d9-2fff59cae1d1.png)

**Comment by jpnurmi** [comment]
Would you prefer to make NavigationPage transparent and stack the whole NavigationPage on top of the TitleBar to get the separator placed into the correct place?

**Comment by jpnurmi** [comment]
What if we would move the "leading" and "trailing" widgets outside the scrollable NavigationRail?

- https://github.com/ubuntu/yaru_widgets.dart/pull/442

**Comment by Jupi007** [comment]
> yeah it's not optimal...
> 
> or something like this

Honestly, this configuration looks even weirder 😅: 

![Capture d’écran du 2022-12-13 21-08-04](https://user-images.githubusercontent.com/36476595/207433712-dfe33b3e-b7dd-4773-9a98-a4bdbbc1d30e.png)

> Would you prefer to make NavigationPage transparent and stack the whole NavigationPage on top of the TitleBar to get the separator placed into the correct place?

Maybe I'm wrong, but it sounds like this wouldn't work for me: if you place a widget on the left of the title bar, the separator will be stacked on top of it isn't it? 🤔

Imo the current situation is quite fine as we can put whatever we want in the titlebar: 

![image](https://user-images.githubusercontent.com/36476595/207435467-a088b8c0-9e64-47d8-b776-2445da9438ca.png)

**Comment by jpnurmi** [comment]
Like this?

![image](https://user-images.githubusercontent.com/140617/207436668-4b49782b-4c88-425c-af1f-b247f657dbaa.png)
![image](https://user-images.githubusercontent.com/140617/207436704-ef3b06e9-0d7c-4150-b6a2-d6b9c8dd4071.png)

**Comment by Jupi007** [comment]
Yaeh, but this small empty space is annoy me 😕
This would be an unusable area.

**Comment by Feichtmeier** [comment]
> Like this?
> 
> ![image](https://user-images.githubusercontent.com/140617/207436668-4b49782b-4c88-425c-af1f-b247f657dbaa.png) ![image](https://user-images.githubusercontent.com/140617/207436704-ef3b06e9-0d7c-4150-b6a2-d6b9c8dd4071.png)

That looks good to me, but I can understand that it might look weird to Paul!

Would it be possible to control what's inside the empty space? If the window is wide enough this could be utilized
I am just brain storming

**Comment by Feichtmeier** [comment]
I think this gritty look can be worked against with the new paned look, not needed to add filled space
