### ISSUE TITLE
Window title bar vs. debug banner

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru.dart#536]
Not sure if there's anything we can do to control the banner location but it's a bit annoying that it goes now over the window controls by default:

![image](https://user-images.githubusercontent.com/140617/212869257-95dd4499-dabc-441e-a110-72d6cd5db3af.png)

**Comment by d-loose** [comment]
It's time to define `YaruApp` with its own custom debug banner!

**Comment by Feichtmeier** [comment]
We could copy the gnomies and add some fancy :skull:  :construction: pattern with opacity to the headerbar :P

**Comment by jpnurmi** [comment]
`YaruApp` would have to forward a painful amount of arguments to `MaterialApp` constructors but it would definitely help us to fix a bunch of things like the debug banner and also to ensure the correct background color (GTK window vs. Yaru Scaffold)...

![image](https://user-images.githubusercontent.com/140617/213696198-17801519-0f03-483a-b195-51c05d20e8ab.png)

**Comment by jpnurmi** [comment]
I documented the workaround in:

- https://github.com/ubuntu/yaru_widgets.dart/pull/639

**Comment by Feichtmeier** [comment]
@d-loose is this still an issue or is the work around enough? (I always turn those off xd)

**Comment by d-loose** [comment]
Personally, I'm perfectly fine with the workaround
