### ISSUE TITLE
Unify borders

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru.dart#588]
Split off from #280.

We should look into unifying the borders in `yaru.dart` and `yaru_widgets.dart`. I'm not sure how's the situation at the moment but there used to be an exhausting amount of different shades/opacities/widths. Feel free to close this if it's no longer relevant. :)

**Comment by Feichtmeier** [comment]
Just use either divider colour or outline now which are the same

**Comment by Feichtmeier** [comment]
should be easier now, and I htink this is almost fixed

**Comment by Feichtmeier** [comment]
I think this is fixed
