### ISSUE TITLE
Add a YaruTab widget

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu/yaru.dart#611]
Something similar to what is shown in the video below though it should be styled in accordance to the more modern Yaru theme :D

https://user-images.githubusercontent.com/73116038/218245107-c148e6f8-15a1-43e8-868a-92f7b909b6be.mp4

**Comment by Feichtmeier** [comment]
hehe :) yes we had one. But we removed it because it was a combination of tabbar and tabbview which does limit this widgets too much because they need to be two widgets 
we could start a new approach with only the tabbar

**Comment by whiskeyPeak** [comment]
> we could start a new approach with only the tabbar

Yeah I agree, that sounds like a better solution. Besides, we don't really need the scrolling feature. Every Gnome application that uses tabs kinda uses it similarly to how a bottom navigation bar works in flutter except with the ability to reorder the tabs and add them on demand.

I'll see if I can get something up and running :)

**Comment by Feichtmeier** [comment]
Oh, I added one some months ago
Fixed :)
