### ISSUE TITLE
YaruWindowTitleBar: clip rounded top corners?

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru.dart#619]
Removing libhandy from the installer resulted in sharp top corners...

![image](https://user-images.githubusercontent.com/140617/218688664-bc1dbaa8-5adf-4386-a580-fb5a308da1df.png)

**Comment by jpnurmi** [comment]
Oh, but that would make an assumption on a specific radius, which might not match the underlying platform...

**Comment by Feichtmeier** [comment]
This is not decided on how to do this and this is not needed anymore when robert succeeds in flutter/flutter/issues/94804, so I close this here
