### ISSUE TITLE
RTL alignment issues

### ISSUE THREAD

**Issue by d-loose** [ubuntu/yaru.dart#690]
I found some more alignment problems with RTL text directionality:

![Screenshot from 2023-04-04 15-24-02](https://user-images.githubusercontent.com/113362648/229807396-36da79aa-92ee-4859-8d1e-8954f977a7f4.png)
![Screenshot from 2023-04-04 15-23-49](https://user-images.githubusercontent.com/113362648/229807422-2028e342-7903-4fed-b50a-ee33cea5e59f.png)
![Screenshot from 2023-04-04 15-23-14](https://user-images.githubusercontent.com/113362648/229807425-0c176a7b-c267-4a6b-a301-244922400824.png)
![Screenshot from 2023-04-04 15-23-03](https://user-images.githubusercontent.com/113362648/229807433-6553c9d8-2349-4476-a888-02f7baed7a9b.png)

**Comment by Feichtmeier** [comment]
@d-loose would you like to have a shot on this one?

**Comment by d-loose** [comment]
Thanks for the ping - I'll try to have a look at this before the end of March!

**Comment by yarons** [comment]
Can you guys post a screenshot please or give us some instructions for testing? Thanks :)

**Comment by d-loose** [comment]
I've included screenshots in my original post. They show yaru.dart's example application with an RTL text direction:

```diff
diff --git a/example/lib/main.dart b/example/lib/main.dart
index f02240e6..2e51d42d 100644
--- a/example/lib/main.dart
+++ b/example/lib/main.dart
@@ -35,7 +35,10 @@ class Home extends StatelessWidget {
           darkTheme: yaru.darkTheme,
           highContrastTheme: yaruHighContrastLight,
           highContrastDarkTheme: yaruHighContrastDark,
-          home: Example.create(context),
+          home: Directionality(
+            textDirection: TextDirection.rtl,
+            child: Example.create(context),
+          ),
           scrollBehavior: const MaterialScrollBehavior().copyWith(
             dragDevices: {
               PointerDeviceKind.mouse,
```

I've spend some time looking into this (see #893), but so far couldn't find an easy fix without diving too deep into the math of `performLayout()` in the custom render object used for `YaruToggleButton`.
I think it'd be worth replacing this with something from the material library instead, since it's very tedious to maintain such low level customizations.

**Comment by yarons** [comment]
@d-loose I meant after the fix :)
Does that affect the direction of the internal part of the button?
Thank you so much for your work 🎊

**Comment by d-loose** [comment]
I've re-opened my PR since I can't reproduce the problems I had yesterday (maybe, I messed something up while testing). There's also a screenshot of the example application with the fix in place. I'd be grateful for any testing!
