### ISSUE TITLE
yaruwindowtitlebar border vs new gtk4 headerbar border

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru.dart#695]
![grafik](https://user-images.githubusercontent.com/15329494/233830781-7aa7c094-32d3-4156-82fa-7b6dfb69acd5.png)

I don't know if this slipped through yaru gnome or if we like this, but the gtk4 theme changed to have a dark headerbar border now

Any opinions and/or impressions on how we want to handle this? Keep as is, change gtk4 theme or change here?

**Comment by Jupi007** [comment]
Honestly, I think it looks better with a dark bottom border.
I tried using `Colors.black.withOpacity(0.25)`.
_I can't post a screenshot cause to my snap problem_

**Comment by Feichtmeier** [comment]
I would agree if the bright border against the dark border wouldn't have such a big contrast. Hmm, hard decision
