### ISSUE TITLE
hovered close button in windows light theme has wrong color

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru.dart#806]
👋 morning

![grafik](https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/b032238f-e69b-4511-b496-ea3d27430017)

could be fixed by catching yet another case inside yaruwindowcontrol but I dont know if you would like this

```dart
Color _getIconColor(ColorScheme colorScheme) {
    if (widget.platform == YaruWindowControlPlatform.windows &&
        widget.type == YaruWindowControlType.close &&
        _hovered) {
      return Colors.white;
    }

    if (widget.foregroundColor != null) {
      return widget.foregroundColor!;
    }

    switch (style) {
      case YaruWindowControlPlatform.yaru:
        return _getYaruIconColor(colorScheme);
      case YaruWindowControlPlatform.windows:
        return _getWindowsIconColor(colorScheme);
    }
  }
```

or by ignoring the foreground color specifically in the titlebar for the close button if the platform is windows

```dart
      if (isClosable == true)
        YaruWindowControl(
          platform: windowControlPlatform,
          foregroundColor: windowControlPlatform ==
                  YaruWindowControlPlatform.windows
              ? null
              : foregroundColor,
          type: YaruWindowControlType.close,
          onTap: onClose != null
              ? () => onClose!(context)
              : null,
        ),
```

![grafik](https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/3a9bb98d-e7d5-4ddf-8988-3a72671743e0)

would you like any of those solutions @Jupi007 ?

**Comment by Jupi007** [comment]
@Feichtmeier I would like to fix it in a little different way :D

**Comment by Feichtmeier** [comment]
okay!
I got two other fixes in the PR then I make a new PR with only those padding and cliprrect changes

**Comment by Jupi007** [comment]
@Feichtmeier I'm sorry, I now realize your fix was the correct way 😅
You can reopen your PR.
The way I wanted to fix this problem would have broke the `foregroundColor` property which should be able to override the icon color in every case.

**Comment by Feichtmeier** [comment]
I think we fixed this
