### ISSUE TITLE
Merge yaru.dart and yaru_icons.dart into this repository

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru.dart#835]
As discussed on discord we want to merge yaru.dart theme and yaru_icons.dart into this repository to avoid the unnecessary maintenance overhead of managing those three depedencies, especially because yaru_widgets has deps to yaru.dart and yaru_icons.dart but also because all of the community and canonical apps use those three libs always together, and never alone.

The plan:

- [X] copy the source code of the icons and the theme to the yaru_widgets.dart repo
- [x] rename yaru.dart and yaru_icons.dart to xx_archive.dart and set them to the archive mode
- [x] then rename yaru_widgets.dart in the repo and pubspec to yaru.dart
- [x] #857
- [x] make a new 4.0.0 release when everything really works
- [x] Help the canonicals migrating their apps, as it is an easy yet big diff to make
CC @d-loose @spydon

**Comment by spydon** [comment]
I can migrate the Canonical repos, as long as none of them are pinned on a previous version, which I know some have been previously.

**Comment by Feichtmeier** [comment]
> [!IMPORTANT]  
> yaru.dart 4.0.0 is now released



Information for canonical flutter contributors on what to do:

- remove yaru_icons and yaru_widgets from pubspec
- replace all imports of yaru_icons.dart and yaru_widgets.dart with just yaru.dart
- in case you were using YaruAnimatedIcon somewhere, the api has changed:
![grafik](https://github.com/ubuntu/yaru.dart/assets/15329494/189d6db9-8dbc-40f4-b8fe-725f0b0c7476)


Here is the diff of this in musicpod as an example:
https://github.com/ubuntu-flutter-community/musicpod/pull/542/files

Was really straight forward
CC @spydon @d-loose @robert-ancell @BLKKKBVSIK

**Comment by Feichtmeier** [comment]
@spydon I think we are done here, or?

**Comment by spydon** [comment]
> @spydon I think we are done here, or?

Probably!
