### ISSUE TITLE
High Contrast accessibility setting does not seem to be toggled across flutter apps

### ISSUE THREAD

**Issue by ghost** [ubuntu/yaru.dart#838]
Related to: https://github.com/ubuntu/app-center/issues/1593

I tested this on another flutter app (musicpod) and it seems to persist there as well so I was wondering if this is a general issue with yaru.dart - is there any other way I could test the high-contrast toggle? 

Thank you very much for your work on this, I'm happy to provide additional information as needed

**Comment by Feichtmeier** [comment]
Related https://github.com/ubuntu/yaru.dart/issues/845

@d-loose could you give me an update what the last status on high contrast was? Since as far as I remember you and JP were the last who worked on this in a time when many things changed

**Comment by d-loose** [comment]
It works reasonably well for the installer - all you need to do is specify the respective themes in `MaterialApp`, see https://github.com/ubuntu/app-center/pull/1610

**Comment by Feichtmeier** [comment]
> It works reasonably well for the installer - all you need to do is specify the respective themes in `MaterialApp`, see [ubuntu/app-center#1610](https://github.com/ubuntu/app-center/pull/1610)

ahhh :D  then I remembered correctly, thank you! I guess we can close this one here then?
I need to do so in other apps then as well

**Comment by ghost** [comment]
Awesome to hear, thanks for getting to this so quickly! 👍🏻
