### ISSUE TITLE
Mismatch between window and scaffold background colors

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru.dart#842]
In dark mode, the window background does not match with scaffold background.

| Active | Inactive |
|---|---|
| ![Screenshot from 2023-01-17 11-32-54](https://user-images.githubusercontent.com/140617/212876305-a00a2ce8-c5e5-4865-8f26-0e7f53bd7338.png) | ![Screenshot from 2023-01-17 11-33-01](https://user-images.githubusercontent.com/140617/212876333-9e222ed7-00d3-49f9-b06e-7c50733c4398.png) |

```dart
import 'package:flutter/material.dart';
import 'package:yaru/yaru.dart';

void main() {
  runApp(
    Padding(
      padding: const EdgeInsets.all(48.0),
      child: YaruTheme(
        builder: (context, yaru, child) {
          return MaterialApp(
            theme: yaru.theme,
            darkTheme: yaru.darkTheme,
            home: const Scaffold(),
          );
        },
      ),
    ),
  );
}
```

**Comment by Feichtmeier** [comment]
@Jupi007 could we code around this in handy_window built in scss tweaks?
Otherwise we should fix this once gtk4 hits

**Comment by Jupi007** [comment]
Hmm, imo the cleanest solution would be to add a background color to the `YaruTheme` widget.

**Comment by Feichtmeier** [comment]
> Hmm, imo the cleanest solution would be to add a background color to the `YaruTheme` widget.

There is always a second where the gtk window is already there but the flutter stuff is not painted yet.

**Comment by Jupi007** [comment]
> There is always a second where the gtk window is already there but the flutter stuff is not painted yet.

Oh, well yeah this can be easily fix in handy_window.
