### ISSUE TITLE
TextField: reduce hover highlight

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru.dart#844]
Would it make sense to drop the hover effect to make it feel less like a button?

[Screencast from 2023-03-06 14-05-31.webm](https://user-images.githubusercontent.com/140617/223118524-5469a9bd-7c89-4123-8069-c2616246c49b.webm)

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/yaru.dart/assets/15329494/a71365bb-b750-4cd1-9904-780365fe8209

I think the highlight is subtle enough and actually great for accessability, closing this
