### ISSUE TITLE
Use hintColor for unselected bottom navigation bar items

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru.dart#847]
> I'm not sure. I understand that you are aligning all the things but this bright white look wrong to me for unselected things. Could you try hintColor?

_Originally posted by @Feichtmeier in https://github.com/ubuntu/yaru.dart/issues/308#issuecomment-1462877616_

> ![Screenshot_20230310-073452.png](https://user-images.githubusercontent.com/15329494/224241508-06961eae-5d2b-45d5-8c8b-cf421480344a.png)
>
> Yes I think this makes more sense. It's bright enough to not look disabled but doesn't grab as much attention as onSurface

_Originally posted by @Feichtmeier in https://github.com/ubuntu/yaru.dart/issues/308#issuecomment-1463342148_

**Comment by Feichtmeier** [comment]
this is a material 2 component and not relevant anymore, navigation bar is now the shizzle, closing
