### ISSUE TITLE
Support GNOME accent colors

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/yaru.dart#908]
GNOME 47 will supports [accent colors](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/adw-accent-color.c?ref_type=heads#L14-29), however this comes with some limitations as the number of colors and their values are limited.

We still have to define a full migration strategy, but ideally we're removing the ubuntu specific colors and use upstream ones.

We *may* tune some of the upstream colors to match the previous colors of us, but this is not yet defined (for sure we'll do it for the orange though).

So, opening this so that we can prepare a migration strategy (we'll need to listen on `xdg-setting` for the value in use), while more details need to come.

For sure yaru.dart will need to support the [same logic](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/adw-accent-color.c?ref_type=heads#L159-199) to get the color to use depending on the xdg-setting value.

**Comment by Feichtmeier** [comment]
Thanks for the heads-up!

When we do this we don't need to drop it for lower specific Ubuntu versions though, right? 
We can keep the themes, they don't harm. But we need a mechanism to detect which theme suite shall be used I guess
I'm not really the low level guy so I fear the new mechanism needs to be implemented by some of you. I can add the new themes though

Edit: if it's dynamic we can already create new themes on the fly, I can post an example

**Comment by 3v1n0** [comment]
FYI we're still tuning the brown accent a bit, so I can give the final colors we're using soon.

In yaru css theme we compute the colors via some contrast optimization function, but once finalized I can give you the final ones

**Comment by Feichtmeier** [comment]
> FYI we're still tuning the brown accent a bit, so I can give the final colors we're using soon.
> 
> In yaru css theme we compute the colors via some contrast optimization function, but once finalized I can give you the final ones

sure, an update with the new color (detection) is now available for your flutter collegues
we can still change it then, just keep me updated in time
