### ISSUE TITLE
Window decoration buttons do not align with desktop settings

### ISSUE THREAD

**Issue by advancingu** [ubuntu/yaru.dart#917]
In a native GNOME 46 session under Ubuntu 24.04.1, when window decoration buttons are configured as left-aligned, this is not reflected in window decorations rendered with yaru.dart. See https://github.com/ubuntu/app-center/issues/792 for related downstream issue.

Additional example:
![Screenshot from 2024-09-01 21-45-24](https://github.com/user-attachments/assets/c24f3437-fa1a-4bda-86da-ff10d86fc5f3)

Button layout configuration:
```bash
$ gsettings get org.gnome.desktop.wm.preferences button-layout
'close,minimize,maximize:'
```

**Comment by Feichtmeier** [comment]
Duplicate of #532
