### ISSUE TITLE
[Question] Is the minimum runtime requirement `org.gnome.Platform`?

### ISSUE THREAD

**Issue by kjxbyz** [ubuntu/yaru.dart#919]
I developed an application and distributed it to `Flathub`. The runtime of the application is `org.freedesktop.Platform`. If I integrate this package, do I need to change the runtime to `org.gnome.Platform`?

Reference: https://docs.flatpak.org/en/latest/available-runtimes.html

**Comment by Feichtmeier** [comment]
> I developed an application and distributed it to `Flathub`. The runtime of the application is `org.freedesktop.Platform`. If I integrate this package, do I need to change the runtime to `org.gnome.Platform`?
> 
> Reference: https://docs.flatpak.org/en/latest/available-runtimes.html

hi, I dont think so. This is just a flutter package, even though there is code to read gtk settings
