### ISSUE TITLE
high contrast themes: `ListTile` selected state is not distinguishable from non-selected state

### ISSUE THREAD

**Issue by d-loose** [ubuntu/yaru.dart#939]
For the high contrast themes the `primaryColor` defaults to either black or white, so that selected `ListTile`s are visually indistinguishable from non-selected ones.

| | Light | Dark |
| - | - | - |
| Normal | ![Screenshot From 2024-10-25 14-03-07](https://github.com/user-attachments/assets/4ba80561-b058-4005-966c-227527d08737) | ![Screenshot From 2024-10-25 14-03-24](https://github.com/user-attachments/assets/6a977789-0ff2-459b-abe4-9a0e4a397e2e) |
| High Contrast | ![Screenshot From 2024-10-25 14-02-18](https://github.com/user-attachments/assets/d9a22229-ba9f-46e3-9c4c-7e5ffb074810) | ![Screenshot From 2024-10-25 14-02-51](https://github.com/user-attachments/assets/cc03e480-745e-4c18-bdd9-4163c5f44c97) |

Minimal example:
```dart
import 'package:flutter/material.dart';
import 'package:yaru/yaru.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return YaruTheme(
      builder: (context, yaru, child) {
        return MaterialApp(
          theme: yaru.theme,
          darkTheme: yaru.darkTheme,
          highContrastTheme: yaruHighContrastLight,
          highContrastDarkTheme: yaruHighContrastDark,
          title: 'Flutter Demo',
          home: Scaffold(
            body: ListView(
              children: const [
                ListTile(
                  selected: true,
                  title: Text('selected tile'),
                ),
                ListTile(
                  selected: false,
                  title: Text('unselected tile'),
                )
              ],
            ),
          ),
        );
      },
    );
  }
}

```

**Comment by Feichtmeier** [comment]
> For the high contrast themes the `primaryColor` defaults to either black or white, so that selected `ListTile`s are visually indistinguishable from non-selected ones.
> 	Light 	Dark
> Normal 	![Screenshot From 2024-10-25 14-03-07](https://private-user-images.githubusercontent.com/113362648/380151019-4ba80561-b058-4005-966c-227527d08737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTkzNjksIm5iZiI6MTcyOTg1OTA2OSwicGF0aCI6Ii8xMTMzNjI2NDgvMzgwMTUxMDE5LTRiYTgwNTYxLWIwNTgtNDAwNS05NjZjLTIyNzUyN2QwODczNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMjI0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDU5Yzk0ZWZkNjcwN2Q0ZTc2MmYwOWRjODhjMTIwNGRlMzI1ZjgzM2E4ZmRkYTZhZGRkNjQyNDk3ZTQzNjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.okFQcWlgZR8k4S3owqAvEu9zMrTXFdGHtjGpOrCJLvo) 	![Screenshot From 2024-10-25 14-03-24](https://private-user-images.githubusercontent.com/113362648/380151016-6a977789-0ff2-459b-abe4-9a0e4a397e2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTkzNjksIm5iZiI6MTcyOTg1OTA2OSwicGF0aCI6Ii8xMTMzNjI2NDgvMzgwMTUxMDE2LTZhOTc3Nzg5LTBmZjItNDU5Yi1hYmU0LTlhMGU0YTM5N2UyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMjI0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDFhNGM5OGE1MzVkOGFhOWQzZDUyMzkyYmM3ZmNiNmYxY2NhYmE2NzliYTU2MTgxNzliZjBkZGM5Mzg5ODg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JeGnPJc2fcMqyFZfEeoGt-4KQF8_1iG1d-rhlvHwzUo)
> High Contrast 	![Screenshot From 2024-10-25 14-02-18](https://private-user-images.githubusercontent.com/113362648/380151027-d9a22229-ba9f-46e3-9c4c-7e5ffb074810.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTkzNjksIm5iZiI6MTcyOTg1OTA2OSwicGF0aCI6Ii8xMTMzNjI2NDgvMzgwMTUxMDI3LWQ5YTIyMjI5LWJhOWYtNDZlMy05YzRjLTdlNWZmYjA3NDgxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMjI0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjdlN2I5NjMwYjQzZWZlNGMxMmZkNzg4MjUxYzMxODBiYTE5MmVhZDhmYjEwYmY0Y2M4YTAyZGQxNmVjODRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ew8fnCebg-DNXs81GDvX8gtBfCmtSTSZjUNALMVK6uo) 	![Screenshot From 2024-10-25 14-02-51](https://private-user-images.githubusercontent.com/113362648/380151021-cc03e480-745e-4c18-bdd9-4163c5f44c97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTkzNjksIm5iZiI6MTcyOTg1OTA2OSwicGF0aCI6Ii8xMTMzNjI2NDgvMzgwMTUxMDIxLWNjMDNlNDgwLTc0NWUtNGMxOC1iZGQ5LTQxNjNjNWY0NGM5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMjI0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWRmMGIyZjRhNjBkY2QwYTEwZmM5NGZlMTliYWNiM2M3ZmU2ZWExMDg5ZjMzNWEyMTkzZGFlN2M5MmNlYjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NXAQyTtteQITgfkeU4ChV0R28d1kNT5FxH0tmj8xsUg)
> 
> Minimal example:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:yaru/yaru.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return YaruTheme(
>       builder: (context, yaru, child) {
>         return MaterialApp(
>           theme: yaru.theme,
>           darkTheme: yaru.darkTheme,
>           highContrastTheme: yaruHighContrastLight,
>           highContrastDarkTheme: yaruHighContrastDark,
>           title: 'Flutter Demo',
>           home: Scaffold(
>             body: ListView(
>               children: const [
>                 ListTile(
>                   selected: true,
>                   title: Text('selected tile'),
>                 ),
>                 ListTile(
>                   selected: false,
>                   title: Text('unselected tile'),
>                 )
>               ],
>             ),
>           ),
>         );
>       },
>     );
>   }
> }
> ```

the listtile theme was somehow traited without much attention because we used a lot of those master tiles
will work on this in the eve
