### ISSUE TITLE
CodeSnippetButton calls "watchPropertyState" but is not a WatchingWidget

### ISSUE THREAD

**Issue by TheLiux** [ubuntu/yaru.dart#963]
I tested the online demo, and when attempting to view the code, a grey screen appeared. This typically indicates an error, so I cloned the repository to investigate further. Here's the error I found:

<img width="1769" alt="Screenshot 2024-11-22 at 10 59 36" src="https://github.com/user-attachments/assets/5b886736-a6b6-4f10-8016-c4a90636ffc2">

I worked on fixing it, and I successfully resolved the issue.
The issue lies in the fact that watch_it functions must be called within a WatchingWidget or a WatchingStatefulWidget.

Currently, _CodeDialog is a StatefulWidget, but honestly, if the example relies on watch_it, most StatefulWidget implementations become unnecessary and resource-intensive.

To address this, I converted the widget from a StatefulWidget to a WatchingWidget, and now it works perfectly. 😃 

> Before:
```dart
class _CodeDialog extends StatefulWidget {
  const _CodeDialog({
    required this.snippetUrl,
  });

  final String snippetUrl;

  @override
  State<_CodeDialog> createState() => _CodeDialogState();
}

class _CodeDialogState extends State<_CodeDialog> {
  late Future<String> _snippet;

  @override
  void initState() {
    super.initState();
    _snippet = di<ExampleModel>().getCodeSnippet(
      widget.snippetUrl,
    );
  }
```

After:
```dart
class _CodeDialog extends WatchingWidget {
  const _CodeDialog({
    required this.snippetUrl,
  });

  final String snippetUrl;

  @override
  Widget build(BuildContext context) {
    final appIsOnline = watchPropertyValue((ExampleModel m) => m.appIsOnline);
    final snippet = di<ExampleModel>().getCodeSnippet(
      snippetUrl,
    );

```

<img width="1769" alt="Screenshot 2024-11-22 at 11 03 26" src="https://github.com/user-attachments/assets/88f0cc68-ac01-45b4-b66f-67634cc0a7bb">

I will open a pull request for this.
PS: May i suggest to use a monospaced font for the `HighlightView` widget?

**Comment by Feichtmeier** [comment]
you only need to add

with WatchItMixin
or the statfeful one,

why 1400+ changed files?

**Comment by TheLiux** [comment]
I pointed on the release one like the template said because is a bugfix. That was strange even for me. If I point on main, you will see less changes.

For the stateful one, honestly why use a `StatefulWidget` when the main purpose of `watch_it` is to avoid `StatefulWidget`?
You obtain the same result if you use `WatchingWidget`

**Comment by Feichtmeier** [comment]
no the main purpose of watch_it, is to re-render certain parts of the tree via listening to property changes in notifiers. 
just add the watchitmixin to the signature of the class. and there is something completely broken in your pull requiest, maybe you are on the old yaru.dart repository? I would suggest to delete your clone and clone a new one from this repository. we made a repo renaming and merged yaru widghets, icons and the theme into the yaru widgets repository (this one here) and renamed it to yaru.dart

**Comment by TheLiux** [comment]
Yes, features that would typically require a StatefulWidget. However, watch_it eliminates that need because you can use a WatchingWidget, which extends StatelessWidget.(or the mixin option, but to be honest, I don’t like it, I prefer using classes, though that’s just a personal preference).

So one of the goal is using StatelessWidget with notifiers, for example like flutter_hooks do.
I can do the StatefulWidget way if this please you, but honestly, is only a waste of performances. 

As for the old and new repositories, here’s what I did: as mentioned in the template, I was targeting the release branch for bug fixes instead of main. That’s why you noticed a lot of changes. Anyway, I deleted the merge request and the old repository, then created a new one. I’ve also added the mixin to the StatefulWidget, though I really dislike this approach.

**Comment by Feichtmeier** [comment]
```dart
    final appIsOnline = watchPropertyValue((ExampleModel m) => m.appIsOnline);

    return AlertDialog(
      titlePadding: EdgeInsets.zero,
      title: YaruDialogTitleBar(
        title: Text(!appIsOnline ? 'Offline' : 'Source code'),
        leading: !appIsOnline
            ? null
            : Center(
                child: YaruIconButton(
                  icon: const Icon(YaruIcons.copy),
                  tooltip: 'Copy',
                  onPressed: () async {
                    await _snippet.then(
                      (value) => Clipboard.setData(
                        ClipboardData(text: value),
                      ),
                    );
                  },
                ),
              ),
      ),
      contentPadding: EdgeInsets.zero,
      content: !appIsOnline
          ? Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const YaruAnimatedVectorIcon(YaruAnimatedIcons.no_network),
                  Padding(
                    padding: const EdgeInsets.symmetric(
                      horizontal: kYaruPagePadding,
                    ),
                    child: Text(
                      'Sorry, you are offline!\nCould not fetch the source code our GitHub repository.',
                      style: Theme.of(context).textTheme.bodyLarge,
                      textAlign: TextAlign.center,
                    ),
                  ),
                ],
              ),
            )
```
    
this only rebuilds if this specific  property "appIsOnline" changes. if you want to move the rebuilds in this dialog further down you need to create seperate widgets for title, content etc, and watch there

watch it holds a list of all properties watched before then compares a new value to the old one and only if it is changed the element which is added to the listeners is marked to rebuild
