### ISSUE TITLE
wrong "icon" color on macOS

### ISSUE THREAD

**Issue by ralph-bergmann** [ubuntu/yaru.dart#971]
I noticed a discrepancy between the web demo version and the current state of the demo app on macOS. The icons of dropdown buttons have a different color. And if you use a color other than "Ubuntu Orange", these icons are not visible (except in the hover state).

Yarn Version (Git hash): 78397bfa

Flutter:
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-x64, locale de-DE)
    • Flutter version 3.27.1 on channel stable at /Users/ralphbergmann/development/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (3 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

<img width="2244" alt="SCR-20241219-lkdv" src="https://github.com/user-attachments/assets/f9b310da-4feb-4b19-ba91-d803a716e03b" />
<img width="2236" alt="SCR-20241219-llkt" src="https://github.com/user-attachments/assets/9b7c20bc-a319-4533-a6d6-323633375f43" />
<img width="2270" alt="SCR-20241219-llus" src="https://github.com/user-attachments/assets/eb440fde-6aeb-4fa2-ae02-e4580d585970" />

**Comment by Feichtmeier** [comment]
@ralph-bergmann thanks for your issue

yaru.dart has not yet been ported to 3.27
on my todo for the holidays though :)
